### ISSUE TITLE
category attribute is not processed

### ISSUE THREAD

**Issue by Alkarex** [marienfressinaud/lib_opml#5]
https://github.com/FreshRSS/FreshRSS/issues/1202

> category is a string of comma-separated slash-delimited category strings, in the format defined by the RSS 2.0 category element. To represent a "tag," the category string should contain no slashes. Examples: 1. category="/Boston/Weather". 2. category="/Harvard/Berkman,/Politics".

http://dev.opml.org/spec2.html

**Comment by marienfressinaud** [comment]
lib\_opml should not change the structure of the given OPML. Moreover, the PR introduces an undesirable behavior. If I'm right, the following OPML:

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<opml version="2.0">
	<head>
		<title>An OPML file</title>
		<dateCreated>Sat, 29 Mar 2014 15:42:42</dateCreated>
	</head>
	<body>
		<outline text="Category A">
			<outline text="My website" type="rss" xmlUrl="https://example.com/feed" category="Category B" />
		</outline>
	</body>
</opml>
```

will be transformed in:

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<opml version="2.0">
	<head>
		<title>An OPML file</title>
		<dateCreated>Sat, 29 Mar 2014 15:42:42</dateCreated>
	</head>
	<body>
		<outline text="Category B">
			<outline text="My website" type="rss" xmlUrl="https://example.com/feed" category="Category B" />
		</outline>
		<outline text="Category A">
		</outline>
	</body>
</opml>
```

This is a big problem because we lose the initial attribution of the feed to "Category A".

As in #3, it is to the caller to handle the case of the `category` attribute. In the case of FRSS, I would rather parse the feeds attached to no categories and look for a category attribute. I can open a PR in the next days.

However, I agree lib\_opml can do something more with the category attribute, and parse it to offer an array of strings.
